// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jSXdcgr_CmXog81iL1ftY4QqXgXci4I',
    appId: '1:116548335116:web:cb75db7899b456e7a7a029',
    messagingSenderId: '116548335116',
    projectId: 'example-a6a87',
    authDomain: 'example-a6a87.firebaseapp.com',
    storageBucket: 'example-a6a87.firebasestorage.app',
    measurementId: 'G-LG40N29WVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS0e25F2qVBygdRuxZ4B82-DhLJZ1tVpQ',
    appId: '1:116548335116:android:d6ac9263f41d286ba7a029',
    messagingSenderId: '116548335116',
    projectId: 'example-a6a87',
    storageBucket: 'example-a6a87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBNuI3Y8BIijYv87BM-b7Zic7yQKw4ZOw',
    appId: '1:116548335116:ios:4dd4ada54da014eda7a029',
    messagingSenderId: '116548335116',
    projectId: 'example-a6a87',
    storageBucket: 'example-a6a87.firebasestorage.app',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBNuI3Y8BIijYv87BM-b7Zic7yQKw4ZOw',
    appId: '1:116548335116:ios:4dd4ada54da014eda7a029',
    messagingSenderId: '116548335116',
    projectId: 'example-a6a87',
    storageBucket: 'example-a6a87.firebasestorage.app',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9jSXdcgr_CmXog81iL1ftY4QqXgXci4I',
    appId: '1:116548335116:web:3c883beb5f764362a7a029',
    messagingSenderId: '116548335116',
    projectId: 'example-a6a87',
    authDomain: 'example-a6a87.firebaseapp.com',
    storageBucket: 'example-a6a87.firebasestorage.app',
    measurementId: 'G-G13N6TESFL',
  );
}
